### ISSUE TITLE
Debugging in Node js from AEM.

### ISSUE THREAD

**Issue by nikhilkumar24dev** [adobe/commerce-cif-graphql-integration-reference#27]
As the code is deployed in Adobe IO point and AEM picks up the data as graphql request from endpoint.
How do we verify the console logs in Node Loader JS file. It doesn't logs as part of chrome logs

**Comment by cjelger** [comment]
Hello. I'm not sure what you exactly mean, but the loader code (if you're talking about files like `ProductLoader.js` etc) runs on I/O Runtime, why do you expect to get logs in Chrome?

**Comment by nikhilkumar24dev** [comment]
I wanted to understand that if I do console.log('Test') in ant Js of adobe IO node code. Where will it be logged ?

**Comment by cjelger** [comment]
This will be logged in the Adobe I/O platform, but successful invocations are no longer logged in Adobe I/O in order to reduce storage space. Check https://www.adobe.io/apis/experienceplatform/runtime/docs.html and https://www.adobe.io/apis/experienceplatform/runtime/docs.html#!adobedocs/adobeio-runtime/master/guides/logging_monitoring.md
